from flask_restful import Api
api = Api()
from .resources import  *

api.add_resource(Login, '/login')
# api.add_resource(Admin, '/admin')
# api.add_resource(Home, '/')
api.add_resource(Signup, '/signup')
api.add_resource(Productslist, '/products')
api.add_resource(Categories, '/categories')
api.add_resource(AddProduct, '/addproduct')
api.add_resource(AddCategory, '/addcategory')
api.add_resource(AddManager, '/addmanager')
api.add_resource(Categorydetails, '/categorydetails/<int:id>')
api.add_resource(Productdetails, '/productdetails/<int:id>')
api.add_resource(Productbycategory, '/productbycategory/<int:id>')
api.add_resource(DeleteProduct, '/deleteproduct/<int:id>')
api.add_resource(DeleteCategory, '/deletecategory/<int:id>')
api.add_resource(EditProduct, '/editproduct/<int:id>')
api.add_resource(EditCategory, '/editcategory/<int:id>')
api.add_resource(CartItems, '/cartitems')
api.add_resource(CartTotal, '/carttotal')
api.add_resource(Billdetails, '/billdetails/<int:id>')
api.add_resource(Billsdetails, '/bills/<int:id>')
api.add_resource(Billtotal, '/billtotal/<int:id>')
api.add_resource(AllBills, '/allbills')
api.add_resource(Billit, '/billit/<int:id>')
api.add_resource(Addtocart, '/addtocart/<int:id>')
api.add_resource(Removefromcart, '/removefromcart/<int:id>')
api.add_resource(Search, '/search/<string:name>')
api.add_resource(Editrequests, '/editrequests')
api.add_resource(Createrequests, '/createrequests')
api.add_resource(Deleterequests, '/deleterequests')
api.add_resource(Managerequests, '/managerequests')
api.add_resource(Editr, '/editr/<int:id>')
api.add_resource(Creater, '/creater/<int:id>')
api.add_resource(Deleter, '/deleter/<int:id>')
api.add_resource(Change, '/change/<string:req_type>')
api.add_resource(Userslist, '/userslist')
api.add_resource(Managerslist, '/managerslist')
api.add_resource(Categorydeleterequest, '/cdr')
api.add_resource(Categoryeditrequest, '/cer')
api.add_resource(Categorycreaterequest, '/ccr')
api.add_resource(Managercreaterequest, '/mcr')
api.add_resource(Userslog, '/userslog')